admin_login_page:
    pattern:  /admin/login
    defaults: { _controller: admin.controller.login:renderLoginPageAction }
    methods:  [GET]

admin_landing_page:
    pattern:  /admin
    defaults: { _controller: admin.controller.landing:renderLandingPageAction }
    methods:  [GET]