admin_ui_login:
    path:  /admin/ui/login
    defaults: { _controller: admin.controller.login:renderLoginAction }
    methods:  [GET]

admin_ui_landing:
    path:  /admin/ui
    defaults: { _controller: admin.controller.landing:renderLandingAction }
    methods:  [GET]

#Blocks
admin_ui_blocks:
    path:  /admin/ui/blocks
    defaults: { _controller: admin.controller.block:renderBlocksAction }
    methods:  [GET]

admin_get_blocks:
    path:  /admin/blocks
    defaults: { _controller: admin.controller.block:getBlocksAction }
    methods:  [GET]

admin_create_block:
    path:  /admin/blocks
    defaults: { _controller: admin.controller.block:createBlockAction }
    methods:  [POST]

admin_edit_block:
    path:  /admin/blocks
    defaults: { _controller: admin.controller.block:editBlockAction }
    methods:  [PUT]

admin_delete_block:
    path:  /admin/blocks/{id}
    defaults: { _controller: admin.controller.block:deleteBlockAction }
    methods:  [DELETE]

admin_get_blocks_by_titles:
    path:  /admin/blocks/titles/{semicolonSeparatedTitles}
    defaults: { _controller: admin.controller.block:getBlocksByTitlesAction }
    methods:  [GET]

#Pages
admin_ui_pages:
    path:  /admin/ui/pages
    defaults: { _controller: admin.controller.page:renderPagesAction }
    methods:  [GET]

admin_ui_pages_add:
    path:  /admin/ui/pages/add
    defaults: { _controller: admin.controller.page:renderPagesAddAction }
    methods:  [GET]

admin_ui_pages_edit:
    path:  /admin/ui/pages/edit/{id}
    defaults: { _controller: admin.controller.page:renderPagesEditAction }
    methods:  [GET]

admin_get_pages:
    path:  /admin/pages
    defaults: { _controller: admin.controller.page:getPagesAction }
    methods:  [GET]

admin_create_page:
    path:  /admin/pages
    defaults: { _controller: admin.controller.page:createPageAction }
    methods:  [POST]

admin_edit_page:
    path:  /admin/pages
    defaults: { _controller: admin.controller.page:editPageAction }
    methods:  [PUT]

admin_delete_page:
    path:  /admin/pages/{id}
    defaults: { _controller: admin.controller.page:deletePageAction }
    methods:  [DELETE]

admin_get_page_blocks:
    path:  /admin/pages/{id}/blocks
    defaults: { _controller: admin.controller.page:getBlocksAction }
    methods:  [GET]

admin_get_pages_by_name_like:
    path:  /admin/pages/name/{name}
    defaults: { _controller: admin.controller.page:getPagesByNameLike }
    methods:  [GET]

#Templates
admin_get_template:
    path:  /admin/templates/{id}
    defaults: { _controller: admin.controller.template:getTemplateAction }
    methods: [GET]