admin_login_page:
    pattern:  /admin/login
    defaults: { _controller: admin.controller.login:renderLoginPageAction }
    methods:  [GET]

admin_landing_page:
    pattern:  /admin
    defaults: { _controller: admin.controller.landing:renderLandingPageAction }
    methods:  [GET]

admin_blocks_page:
    pattern:  /admin/manage-blocks
    defaults: { _controller: admin.controller.blocks:renderManagePageAction }
    methods:  [GET]

admin_retrieve_blocks:
    pattern:  /admin/blocks
    defaults: { _controller: admin.controller.blocks:retrieveBlocksAction }
    methods:  [GET]