admin_login_page:
    pattern:  /admin/login
    defaults: { _controller: admin.controller.login:renderLoginPageAction }
    methods:  [GET]

admin_landing_page:
    pattern:  /admin
    defaults: { _controller: admin.controller.landing:renderLandingPageAction }
    methods:  [GET]

#Blocks
admin_blocks_page:
    pattern:  /admin/manage-blocks
    defaults: { _controller: admin.controller.blocks:renderManagePageAction }
    methods:  [GET]

admin_retrieve_blocks:
    pattern:  /admin/blocks
    defaults: { _controller: admin.controller.blocks:retrieveBlocksAction }
    methods:  [GET]

admin_save_block:
    pattern:  /admin/blocks
    defaults: { _controller: admin.controller.blocks:saveBlockAction }
    methods:  [POST]

admin_delete_block:
    pattern:  /admin/blocks/{id}
    defaults: { _controller: admin.controller.blocks:deleteBlockAction }
    methods:  [DELETE]

#Pages
admin_pages_page:
    pattern:  /admin/manage-pages
    defaults: { _controller: admin.controller.pages:renderManagePageAction }
    methods:  [GET]

admin_retrieve_pages:
    pattern:  /admin/pages
    defaults: { _controller: admin.controller.pages:retrievePagesAction }
    methods:  [GET]

#Templates
admin_get_complete_template:
    pattern:  /admin/templates/{id}
    defaults: { _controller: admin.controller.templates:getCompleteTemplateAction }
    methods: [GET]