admin_ui_login:
    pattern:  /admin/ui/login
    defaults: { _controller: admin.controller.login:renderLoginAction }
    methods:  [GET]

admin_ui_landing:
    pattern:  /admin/ui
    defaults: { _controller: admin.controller.landing:renderLandingAction }
    methods:  [GET]

#Blocks
admin_ui_blocks:
    pattern:  /admin/ui/blocks
    defaults: { _controller: admin.controller.blocks:renderBlocksAction }
    methods:  [GET]

admin_retrieve_blocks:
    pattern:  /admin/blocks
    defaults: { _controller: admin.controller.blocks:retrieveBlocksAction }
    methods:  [GET]

admin_save_block:
    pattern:  /admin/blocks
    defaults: { _controller: admin.controller.blocks:saveBlockAction }
    methods:  [POST]

admin_delete_block:
    pattern:  /admin/blocks/{id}
    defaults: { _controller: admin.controller.blocks:deleteBlockAction }
    methods:  [DELETE]

admin_get_blocks_by_titles:
    pattern:  /admin/blocks/titles/{semicolonSeparatedTitles}
    defaults: { _controller: admin.controller.blocks:getBlocksByTitlesAction }
    methods:  [GET]

#Pages
admin_ui_pages:
    pattern:  /admin/ui/pages
    defaults: { _controller: admin.controller.pages:renderPagesAction }
    methods:  [GET]

admin_ui_pages_add:
    pattern:  /admin/ui/pages/add
    defaults: { _controller: admin.controller.pages:renderPagesAddAction }
    methods:  [GET]

admin_ui_pages_edit:
    pattern:  /admin/ui/pages/edit/{id}
    defaults: { _controller: admin.controller.pages:renderPagesEditAction }
    methods:  [GET]

admin_get_pages:
    pattern:  /admin/pages
    defaults: { _controller: admin.controller.pages:getPagesAction }
    methods:  [GET]

admin_save_page:
    pattern:  /admin/pages
    defaults: { _controller: admin.controller.pages:savePageAction }
    methods:  [POST]

admin_get_page_blocks:
    pattern:  /admin/pages/{id}/blocks
    defaults: { _controller: admin.controller.pages:getBlocksAction }
    methods:  [GET]

admin_get_pages_by_name_like:
    pattern:  /admin/pages/name/{name}
    defaults: { _controller: admin.controller.pages:getPagesByNameLike }
    methods:  [GET]

#Templates
admin_get_template:
    pattern:  /admin/templates/{id}
    defaults: { _controller: admin.controller.templates:getTemplateAction }
    methods: [GET]