parameters:
    admin.service.response.class:         Swifter\AdminBundle\Service\ResponseService
    admin.service.serialization.class:    Swifter\AdminBundle\Service\SerializationService
    admin.service.crud.class:             Swifter\AdminBundle\Service\CrudService
    admin.service.page.crud.class:        Swifter\AdminBundle\Service\PageCrudService
    admin.service.block.class:            Swifter\AdminBundle\Service\BlockService
    admin.controller.login.class:         Swifter\AdminBundle\Controller\LoginController
    admin.controller.landing.class:       Swifter\AdminBundle\Controller\LandingController
    admin.controller.block.class:         Swifter\AdminBundle\Controller\BlockController
    admin.controller.page.class:          Swifter\AdminBundle\Controller\PageController
    admin.controller.template.class:      Swifter\AdminBundle\Controller\TemplateController

services:
    admin.service.response:
        class: %admin.service.response.class%

    admin.service.serialization:
        class: %admin.service.serialization.class%
        arguments: ["@service_container"]

    admin.service.crud:
        class: %admin.service.crud.class%
        arguments: ["@admin.service.response", "@doctrine.orm.entity_manager"]

    admin.service.page.crud:
        class: %admin.service.page.crud.class%
        arguments: ["@admin.service.response", "@common.service.pageBlock", "@doctrine.orm.entity_manager"]

    admin.service.block:
        class: %admin.service.block.class%
        arguments: ["@doctrine.orm.entity_manager"]

    admin.controller.template:
        class: %admin.controller.template.class%
        arguments: ["@common.service.template", "@admin.service.response"]
        calls:
            -  [setContainer, ["@service_container"]]

    admin.controller.login:
        class: %admin.controller.login.class%
        calls:
            -  [setContainer, ["@service_container"]]

    admin.controller.landing:
        class: %admin.controller.landing.class%
        calls:
            -  [setContainer, ["@service_container"]]

    admin.controller.block:
        class: %admin.controller.block.class%
        arguments: ["@admin.service.crud", "@admin.service.response", "@admin.service.serialization", "@admin.service.block"]
        calls:
            -  [setContainer, ["@service_container"]]

    admin.controller.page:
        class: %admin.controller.page.class%
        arguments: ["@admin.service.page.crud", "@admin.service.response", "@admin.service.serialization", "@common.service.pageBlock", "@common.service.page"]
        calls:
            -  [setContainer, ["@service_container"]]

