parameters:
    swifter_admin.controller.login.class: Swifter\AdminBundle\Controller\LoginController

services:
    swifter_admin.controller.login:
        class: %swifter_admin.controller.login.class%
        calls:
            -  [setContainer, ["@service_container"]]