parameters:
    admin.controller.login.class: Swifter\AdminBundle\Controller\LoginController
    admin.controller.landing.class: Swifter\AdminBundle\Controller\LandingController
    admin.controller.blocks.class:  Swifter\AdminBundle\Controller\BlocksController
    admin.controller.pages.class:  Swifter\AdminBundle\Controller\PagesController

services:
    admin.controller.login:
        class: %admin.controller.login.class%
        calls:
            -  [setContainer, ["@service_container"]]

    admin.controller.landing:
          class: %admin.controller.landing.class%
          calls:
              -  [setContainer, ["@service_container"]]

    admin.controller.blocks:
              class: %admin.controller.blocks.class%
              calls:
                  -  [setContainer, ["@service_container"]]

    admin.controller.pages:
              class: %admin.controller.pages.class%
              calls:
                  -  [setContainer, ["@service_container"]]