swifter_front_dispatcher:
    path:  /{uri}
    defaults: { _controller: front.controller.dispatcher:indexAction, uri: "" }
    requirements:
        uri:  "[\sa-zA-Z0-9\-\/\.]*"
    methods:  [GET]

