swifter_front_dispatcher:
    pattern:  /{uri}
    defaults: { _controller: swifter_front.controller.dispatcher:indexAction, uri: "" }
    requirements:
        uri:  "[\sa-zA-Z0-9\-\/\.]*"
    methods:  [GET]

