parameters:
    swifter.front.controller.dispatcher.class: Swifter\FrontBundle\Controller\DispatcherController
    swifter.front.service.snippet.class: Swifter\FrontBundle\Service\SnippetService

services:
    swifter.front.service.snippet:
        class: %swifter.front.service.snippet.class%

    swifter.front.controller.dispatcher:
        class: %swifter.front.controller.dispatcher.class%
        arguments: ["@swifter.front.service.snippet"]
        calls:
            -  [setContainer, ["@service_container"]]

