parameters:
    front.controller.dispatcher.class: Swifter\FrontBundle\Controller\DispatcherController
    front.service.snippet.class: Swifter\FrontBundle\Service\SnippetService
    front.service.devtest.class: Swifter\FrontBundle\Service\DevTestService

services:
    front.service.devtest:
        class: %front.service.devtest.class%
        arguments: ["@doctrine.orm.entity_manager"]

    front.service.snippet:
        class: %front.service.snippet.class%
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    front.controller.dispatcher:
        class: %front.controller.dispatcher.class%
        arguments: ["@twig", "@front.service.snippet"]
        calls:
            -  [setContainer, ["@service_container"]]

