parameters:
    swifter_front.controller.dispatcher.class: Swifter\FrontBundle\Controller\DispatcherController
    swifter_front.service.snippet.class: Swifter\FrontBundle\Service\SnippetService
    swifter_front.service.devtest.class: Swifter\FrontBundle\Service\DevTestService

services:
    swifter_front.service.devtest:
        class: %swifter_front.service.devtest.class%
        arguments: ["@doctrine.orm.entity_manager"]

    swifter_front.service.snippet:
        class: %swifter_front.service.snippet.class%
        arguments: ["@service_container"]

    swifter_front.controller.dispatcher:
        class: %swifter_front.controller.dispatcher.class%
        arguments: ["@swifter_front.service.snippet"]
        calls:
            -  [setContainer, ["@service_container"]]

