imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        doctrine:
              bubble: false
              action_level: DEBUG
              type:  stream
              path:  %kernel.logs_dir%/%kernel.environment%_doctrine.log
              channels: doctrine
        event_all:
              bubble: false
              action_level: DEBUG
              type:  stream
              path:  %kernel.logs_dir%/%kernel.environment%_event_all.log
              channels: event
        event_errors:
            action_level: ERROR
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%_event_errors.log
            channels: event
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: DEBUG

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com
