swifter_admin:
    resource: "@SwifterAdminBundle/Resources/config/routing.yml"
    prefix:   /

swifter_user:
    resource: "@SwifterUserBundle/Resources/config/routing.yml"
    prefix:   /

swifter_front:
    resource: "@SwifterFrontBundle/Resources/config/routing.yml"
    prefix:   /