security:
    encoders:
        Swifter\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        swifter_user_provider:
            entity: { class: SwifterUserBundle:User, property: email }

    firewalls:
        admin_area:
            pattern:    ^/admin
            provider: swifter_user_provider
            form_login:
                check_path: swifter_login
                login_path: swifter_login_form
                username_parameter: email
                password_parameter: password
            logout:
                path:   swifter_logout
                target: swifter_login
            anonymous: ~

    access_control:
            - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
