security:
    encoders:
        Swifter\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        swifter_user_provider:
            entity: { class: SwifterUserBundle:User, property: email }

    firewalls:
        admin_area:
            pattern:    ^/
            provider: swifter_user_provider
            form_login:
                check_path: login
                login_path: admin_ui_login
                username_parameter: email
                password_parameter: password

                default_target_path: admin_ui_landing
                use_referer: false
                always_use_default_target_path: true
                #csrf
                csrf_provider: form.csrf_provider
                csrf_parameter: _csrf_security_token
                intention: authenticate

            logout:
                path:   logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 7 days in seconds
                path:     /
                domain:   ~
            anonymous: ~

    access_control:
            - { path: ^/admin/ui/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
