swifter_login_form:
    pattern:  /admin/login
    defaults: { _controller: swifter_user.controller.login:renderLoginPageAction }
    methods:  [GET]

swifter_login:
    pattern:  /login
    methods:  [POST]

swifter_logout:
    pattern: /logout