parameters:
#    swifter_user.example.class: Swifter\UserBundle\Example

services:
#    swifter_user.example:
#        class: %swifter_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
